version: '3.7'

services:
  mariadb:
    image: 'docker.${KITT_DOMAIN}/bitnami/mariadb:10.3'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    env_file: .env
  wordpress:
    image: 'docker.${KITT_DOMAIN}/bitnami/wordpress:5.5.0'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.entrypoints=https"
      - "traefik.http.routers.wordpress.rule=Host(`press.${KITT_DOMAIN}`)"
      - "traefik.http.services.wordpress.loadbalancer.server.port=8080"

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  default:
    external:
      name: kitt
