version: '3.7'

services:
  wordpress:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`wordpress.whoa.bot`,`wordpress.defn.sh`)"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"

networks:
  default:
    external:
      name: kitt
